name: Publish release on tag push

on:
  push:
    branches: [ main ]
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - uses: softprops/action-gh-release@v0.1.14
        with:
          prerelease: true
          body: Automatic release created by GitHub Action.
          files: dist/styles/**
